name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    defaults:
      run:
        working-directory: web
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-web
        with:
          # pnpm cache files are stored in `~/.pnpm-store` on Linux/macOS
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install dependencies
        run: pnpm install

      - name: Build apps
        run: pnpm nx run-many --target=build --projects=host,home

      - uses: actions/upload-artifact@v2
        name: Upload Artifact
        with:
          name: dist
          path: /home/runner/work/awdware3/awdware3/web/dist
          if-no-files-found: error

  test:
    defaults:
      run:
        working-directory: tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-tests
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install dependencies
        run: pnpm

      - uses: actions/download-artifact@master
        name: Download Artifact
        with:
          name: dist
          path: web/dist

      - name: Copy build into tests/dist folder
        run: mkdir -p dist && cp -r ../web/dist/apps/host/** ./dist && mkdir -p dist/assets/modules && cp -r ../web/dist/apps/home ./dist/assets/modules && ls -R ./dist

      - name: Copy test config files
        run: pnpm run copy-cfg

      - name: Install playwright
        run: pnpm playwright install

      - name: Run Playwright tests
        run: pnpm run test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: /home/runner/work/awdware3/awdware3/tests/playwright-report/
          retention-days: 30
