name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    defaults:
      run:
        working-directory: web
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn
      - name: Build apps
        run: yarn nx run-many --target=build --projects=host,home
      - uses: actions/upload-artifact@master
        name: Upload Artifact
        with:
          name: dist
          path: dist

  test:
    defaults:
      run:
        working-directory: test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: yarn
      - uses: actions/download-artifact@master
        name: Download Artifact
        with:
          name: dist
          path: ../web/dist
      - name: Copy build into tests/dist folder
        run: yarn run prepare-dist
      - name: Copy test config files
        run: yarn run copy-cfg
      - name: Run Playwright tests
        run: yarn run test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
